[tool.poetry]
name = "aoc2024"
version = "0.1.0"
description = ""
authors = ["Sev <sevend.osmanko@rvu.co.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
